### ISSUE TITLE
FR: Allow (via automation) to start listening again (without wakeword) after SND

### ISSUE THREAD

**Issue by tbrasser** [AlexxIT/StreamAssist#10]
Currently after SND stage is done, I have to start over by speaking the wakeword, and then there is no context of the previous pipeline run.

Would it be possible to go back to STT after SND. (with a timeout on silence)? 
Or maybe there is a more elegant/effective way to do this.

**Comment by AlexxIT** [comment]
There is no more SND stage in v2

**Comment by tbrasser** [comment]
Sorry, I just meant to look for a way to continue the conversation instead of starting at wakeword again.

**Comment by AlexxIT** [comment]
Well. How you start first pipeline? Via MIC switch or via service?

**Comment by tbrasser** [comment]
Ah, I can catch something like a pipeline or conversation id and call the run service with that id with STT as start stage? I'll try some things out. 👍

**Comment by AlexxIT** [comment]
You not answer on my question

**Comment by tbrasser** [comment]
I toggle the mic switch via an automation.

**Comment by AlexxIT** [comment]
Well. If you remove WAKE setting from pipeline config - it will start from STT stage.
If you want start from WAKE but continue with STT - you can create two pipelines. Then stop one and start another...

**Comment by tbrasser** [comment]
Basically I'm looking for an equivalent of this: https://esphome.io/components/voice_assistant.html#voice-assistant-start-continuous

**Comment by IoSonoAndreaZ** [comment]
> Well. If you remove WAKE setting from pipeline config - it will start from STT stage. If you want start from WAKE but continue with STT - you can create two pipelines. Then stop one and start another...

care to explain more? it is not clear, sorry

**Comment by nirnachmani** [comment]
@AlexxIT, on this topic, I start my first streamassist (called 'livingroom-tablet') pipeline via mic.

I want to write an automation which will start after the livingroom-tablet streamassist tts ends, and as an action will start the same streamassist from stt so it will listen to my next voice command. 

In the automation I can call the stream_assist.run service (as in my example below), but how do I call my livingroom-tablet streamassist and start it from stt?

If the automation starts a new streamassist service, it will not continue to the next cycle as it will not trigger the automation (only sensor.livingroom_tablet_tts triggers it). 

If I do what you suggested above - two streamassists, one that starts with mic, the other with stt, how do I start the second one from an automation?

What am I missing?

For reference, this is what I have now, which doesn't work:
```
- id: stream_assist_livingroom_continuous_conversation
  alias: stream_assist_livingroom_continuous_conversation
  trigger:
  - platform: state
    entity_id: sensor.livingroom_tablet_tts
    from: 'start'
    to: 'end'
  action:
  - service: stream_assist.run
    data:
      stream_source: rtp://192.168.1.71:55555
      player_entity_id: media_player.galaxy_tab_s2
      pipeline_id: 01j2nty2rmw17n7rzfvcvk25x9
      assist:
        start_stage: stt
        end_stage: tts
```

Thanks
