### ISSUE TITLE
Won't Work with Tapo C110 & C200

### ISSUE THREAD

**Issue by Gompman** [AlexxIT/StreamAssist#13]
Hello, the possibility to use the camera stream is fantastic. But unfortunately it does not work for me. Tested via the Tapo integration (models C110 & 2x C200) and via the restream from frigate with audio in aac. Only via Android IP camera it works. How can I debug? 
However, the video stream in Homeassistant of the cameras has sound.

Maybe someone can help me.

**Comment by AlexxIT** [comment]
Check logs

**Comment by relust** [comment]
I use Tapo c100 with Stream Assist directly with rtsp link and it works very well 
rtsp://administrator:password@192.168.0.xxx:554/stream2 

My question is if it would be possible to make the media player functional with the help of go2rtc to also play the answer on the tapo camera.

**Comment by AlexxIT** [comment]
go2rtc supports two way for Tapo cameras via tapo protocol

**Comment by Gompman** [comment]
I now also have the camera directly via `rtsp://user:password@192.168.xxx.xxx:554/stream2`conected.
Here I get in the logs: "<class 'av.error.PermissionError'>: [Errno 1] Operation not permitted:" if I open the same stream via VLC I have picture and sound.

The variant behind Frigate gives the following error: "stream exception <class 'av.error.OSError'>: [Errno 5] I/O error: 'rtsp://192.168.xxx.xxx:8554/Office'". Also possible to watch via VLC

Frigate config:
```
....
go2rtc:
  streams:
    Office: # <- for RTSP streams
      - tapo://CloudPW@192.168.xxx.xxx
      - "ffmpeg:Office#audio=aac"

##### Büro Stream Assist #####
cameras:
  Office:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Office # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
    record:
      enabled: False
....
```
