### ISSUE TITLE
[New Feature] - Create extra two entries with question and response text

### ISSUE THREAD

**Issue by witold-gren** [AlexxIT/StreamAssist#15]
Hi @AlexxIT, thanks for really great plugin. 

Could you create an additional entities that would store the last processed query and response? eg. `Last question` and `Last response` for each configured stream? This would really help a lot in streamlining and customizing text and response processing.. 

PS. Also it would be really nice to add the ability to set the end of sentence recognition (eg. Default, Aggressive). I noticed that when there is a slight noise in the background, the text is constantly being processed even if I finish speak sentence.. process wait for complete silence to stop processing sound.

**Comment by AlexxIT** [comment]
I think you can create any additional entities with helpers and triggers.

**Comment by witold-gren** [comment]
I don't know the architecture of Home Assistant that well. I can try but it may take a while 😉

**Comment by bkbilly** [comment]
You can use an automation with a trigger like this:
```yaml
platform: event
event_type: state_changed
event_data:
  entity_id: sensor.name_of_camera_intent  # Replace name_of_camera with your stream_assist device name
```
