### ISSUE TITLE
MIC wont stay on

### ISSUE THREAD

**Issue by janstadt** [AlexxIT/StreamAssist#33]
I have 3 audio streams from Lenovo ThinkSmart (via IP Webcam app, but i've also noticed this in other apps) and the MIC will not stay on. I have an automation run if it detects the mic isnt on and toggles it, but when i restart HA its always off. I can update that automation to also be triggered by uptime, but i was wondering if this is by design or if something is wrong with the intergration? I'd love for it to be always on UNLESS i turn it off as opposed to the opposite.

**Comment by janstadt** [comment]
I also noticed that it turns off after i reconfigured the integration.

**Comment by xvlw** [comment]
While not a fix, this is the workaround that I put in place as an automation


```
alias: Stream Assist Mic
description: Turns on Stream Assist Mic if it is turned off
trigger:
  - platform: state
    entity_id:
      - switch.streamassist_<mic entity name>
    from: "on"
    to: "off"
  - platform: homeassistant
    event: start
condition: []
action:
  - service: switch.turn_on
    target:
      entity_id:
        - switch.streamassist_<mic entity name>
    data: {}
mode: single
```
